// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;
using UnityEngine.UI;
namespace AssemblyCSharp
{
	public class ButtonNextLevel: MonoBehaviour
	{
		public Image partOne;
		public Image partTwo;
		public Image partThree;

		public Image Loop;
		public Image Drop;
		public Image Pretzel;
		public Image Screw;
		public Image Spiral;
		public Image Cobra;


		void Start()
		{
			partOne   = partOne.GetComponent<Image>();
			partTwo   = partTwo.GetComponent<Image>();
			partThree = partThree.GetComponent<Image>();
		}
		public void NextLevelButton (int index)
		{
			if(partOne != null)
			{
				Debug.Log(partThree.overrideSprite);
				Debug.Log (Spiral.sprite);
				Debug.Log (partThree.overrideSprite == Spiral.sprite);
				if( partOne.overrideSprite == Loop.sprite && partTwo.overrideSprite == Spiral.sprite && partThree.overrideSprite == Screw.sprite )
				{
					ApplicationModel.splineLevel = 1;
					//Debug.Log("yes");
				}
				else if( partOne.overrideSprite == Loop.sprite && partThree.overrideSprite == Drop.sprite && partTwo.overrideSprite == Screw.sprite )
				{
					//Debug.Log ("er");
					ApplicationModel.splineLevel = 2;
				}
			}

			Application.LoadLevel (index);
		}
		public void NextLevelButton (string levelName)
		{
			Application.LoadLevel (levelName);
		}
	}
}

