// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;
using UnityEngine.UI;
namespace AssemblyCSharp
{
	public class ButtonNextLevel: MonoBehaviour
	{
		public Image partOne;
		public Image partTwo;
		public Image partThree;

		public Image Loop;
		public Image Drop;
		public Image Pretzel;
		public Image Twist;
		public Image Screw;
		public Image Cobra;


		void Start()
		{
			partOne   = partOne.GetComponent<Image>();
			partTwo   = partTwo.GetComponent<Image>();
			partThree = partThree.GetComponent<Image>();
		}
		public void NextLevelButton (int index)
		{
			Debug.Log(partOne.overrideSprite);
			if( partOne.overrideSprite == Loop.sprite && partTwo.overrideSprite == Twist.sprite && partThree.overrideSprite == Screw )
			{
				ApplicationModel.splineLevel = 1;
				Debug.Log("yes");
			}
			else if( partOne.overrideSprite == Loop.sprite && partTwo.overrideSprite == Twist.sprite && partThree.overrideSprite == Screw )
			{
				ApplicationModel.splineLevel = 2;
			}

/*			Application.LoadLevel (index);
*/		}
		public void NextLevelButton (string levelName)
		{
			Application.LoadLevel (levelName);
		}
	}
}

