// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;
namespace AssemblyCSharp
{
	public class ButtonNextLevel: MonoBehaviour
	{
		public void NextLevelButton (int index)
		{
			Application.LoadLevel (index);
		}
		public void NextLevelButton (string levelName)
		{
			Application.LoadLevel (levelName);
		}
	}
}

